In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('laptop_price.csv', encoding='unicode_escape')

In [3]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

# Exercise 1

 Task: Find the biggest and smallest screen size in laptops of each company using the sort_values() and duplicated() methods (keep "first", "last" and False)

In [4]:
# sort dataframe asending by company and inches
df.sort_values(['Inches','Company'])

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
50,51,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Android,0.69kg,319.00
1082,1097,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Windows 10,0.69kg,646.27
1114,1129,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Android,0.69kg,549.00
1126,1141,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Windows 10,0.69kg,479.00
944,958,Lenovo,Yoga 700-11ISK,2 in 1 Convertible,11.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core M m7-6Y75 1.2GHz,8GB,256GB SSD,Intel HD Graphics 515,Windows 10,1.1kg,1299.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1212,1230,MSI,GS73VR Stealth,Gaming,17.3,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.43kg,1948.99
1233,1251,MSI,GE72VR Apache,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.7kg,1598.00
196,200,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,1TB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6099.00
830,839,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,512GB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,5499.00
177,181,MSI,GT80S 6QF-074US,Gaming,18.4,Full HD 1920x1080,Intel Core i7 6920HQ 2.9GHz,32GB,512GB SSD + 1TB HDD,Nvidia GTX 980 SLI,Windows 10,4.4kg,2799.00

In [5]:
# smallest: keep='first'
sort = df.sort_values(['Company', 'Inches'])
sort.drop_duplicates(['Company'])[['Company', 'Inches']]

        Company  Inches
319        Acer    11.6
1234      Apple    11.6
20         Asus    11.6
421       Chuwi    12.3
455        Dell    11.6
567     Fujitsu    15.6
437      Google    12.3
677          HP    11.6
170      Huawei    13.0
909          LG    14.0
50       Lenovo    10.1
785         MSI    14.0
429    Mediacom    11.6
70    Microsoft    13.5
816       Razer    12.5
430     Samsung    11.6
963     Toshiba    12.5
1120       Vero    13.3
192      Xiaomi    13.3

In [6]:
sort.drop_duplicates(['Company'], keep='last')[['Company', 'Inches']]

        Company  Inches
1216       Acer    17.3
17        Apple    15.4
1256       Asus    17.3
483       Chuwi    15.6
1243       Dell    17.3
983     Fujitsu    15.6
762      Google    12.3
1136         HP    17.3
214      Huawei    13.0
905          LG    15.6
1217     Lenovo    17.3
177         MSI    18.4
718    Mediacom    14.0
670   Microsoft    13.5
830       Razer    17.3
593     Samsung    15.6
1042    Toshiba    15.6
1041       Vero    14.0
514      Xiaomi    15.6

In [23]:
leno=df[df['Company']=='Acer'][['Company', 'Inches']]

In [24]:
leno.sort_values('Inches')['Inches']

619     11.6
560     11.6
461     11.6
695     11.6
319     11.6
        ...
730     17.3
788     17.3
1208    17.3
1189    17.3
1216    17.3
Name: Inches, Length: 103, dtype: float64