In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

# sample()

In [12]:
# give some sample rows 0.2=> 20% of rows of original df
# random_state=50 gives same sample if we run how many times also (99, 50 oru wish)
df.sample(frac=0.2, random_state=50)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Reis,Ludovit Reis,19,2000-06-01,178,75,Netherlands,FC Barcelona
A. Herrera,Aaron Herrera,22,1997-06-06,180,70,United States,Real Salt Lake
J. Kurtić,Jasmin Kurtić,30,1989-01-10,186,88,Slovenia,SPAL
A. Wisdom,Andre Wisdom,26,1993-05-09,186,78,England,Derby County
J. Caicedo,Juan Caicedo,29,1989-07-13,187,79,Colombia,New England Revolution
...,...,...,...,...,...,...,...
G. Lionetti,Giorgio Lionetti,21,1998-05-09,176,70,Italy,Castellammare di Stabia
K. Riascos,Kevin Riascos,24,1995-06-21,183,82,Colombia,Jaguares de Córdoba
W. Horlison,Wayne Horlison,27,1992-02-29,180,75,England,Bury
M. Saracchi,Marcelo Josemir Saracchi Pintos,21,1998-04-23,172,69,Uruguay,RB Leipzig
F. Ibsen,Frederik Ibsen,22,1997-03-28,194,81,Denmark,FC København

In [14]:
# frac=2 => 200% of sample double the original df
# replace=True => for 200% of data the repetation of row required so replace=True allows to make repetaion
# random_state=99 => give same sample no matter how many times we run
df.sample(frac=2, replace=True, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle
A. Mosquera,Andrés Mosquera,29,1990-02-20,182,80,Colombia,Club León
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US Orléans Loiret Football
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Étienne
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC
...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna Düsseldorf
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors