In [1]:
import pandas as pd

# 1 Read a .csv form a URL with Pandas

Target Website :-https://www.football-data.co.uk/data.php

In [2]:
# reading the csv file
df_main = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/P1.csv')
df_main

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,P1,08/08/2025,20:15,Casa Pia,Sp Lisbon,0,2,A,0,1,...,1.93,1.93,1.90,2.00,1.93,1.95,1.82,1.92,1.91,2.04
1,P1,09/08/2025,15:30,Nacional,Gil Vicente,0,2,A,0,2,...,1.80,2.05,1.89,2.02,1.83,2.05,1.78,1.97,1.87,2.12
2,P1,09/08/2025,20:30,Arouca,AVS,3,1,H,1,0,...,1.98,1.88,1.97,1.93,1.98,1.90,1.90,1.79,2.02,1.95
3,P1,10/08/2025,17:00,Famalicao,Santa Clara,3,0,H,2,0,...,1.93,1.93,2.00,1.90,1.93,1.93,1.78,1.89,1.93,2.05
4,P1,10/08/2025,20:30,Moreirense,Alverca,2,1,H,1,1,...,1.95,1.90,2.05,1.87,1.95,1.90,1.88,1.84,2.05,1.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,P1,27/09/2025,20:30,Estoril,Sp Lisbon,0,1,A,0,1,...,1.98,1.88,2.03,1.87,1.98,1.88,1.92,1.81,2.01,1.93
59,P1,28/09/2025,15:30,Alverca,Guimaraes,2,0,H,1,0,...,1.83,2.03,1.97,1.93,1.91,2.03,1.82,1.93,1.96,2.01
60,P1,28/09/2025,18:00,Sp Braga,Nacional,0,1,A,0,1,...,1.95,1.90,1.88,2.03,1.95,1.90,1.86,1.86,1.99,1.94
61,P1,28/09/2025,20:30,Famalicao,Rio Ave,0,0,D,0,0,...,1.83,2.03,1.87,2.05,1.85,2.03,1.81,1.91,1.93,2.04
62,P1,29/09/2025,20:00,Arouca,Porto,0,4,A,0,1,...,1.95,1.90,1.82,2.09,1.95,2.07,1.85,1.89,1.99,1.99

In [3]:
# renaming the columns 
df_main.rename(columns={'FTHG':'home score',
                        'FTAG':'away score' },
               inplace=True)
df_main

,Div,Date,Time,HomeTeam,AwayTeam,home score,away score,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,P1,08/08/2025,20:15,Casa Pia,Sp Lisbon,0,2,A,0,1,...,1.93,1.93,1.90,2.00,1.93,1.95,1.82,1.92,1.91,2.04
1,P1,09/08/2025,15:30,Nacional,Gil Vicente,0,2,A,0,2,...,1.80,2.05,1.89,2.02,1.83,2.05,1.78,1.97,1.87,2.12
2,P1,09/08/2025,20:30,Arouca,AVS,3,1,H,1,0,...,1.98,1.88,1.97,1.93,1.98,1.90,1.90,1.79,2.02,1.95
3,P1,10/08/2025,17:00,Famalicao,Santa Clara,3,0,H,2,0,...,1.93,1.93,2.00,1.90,1.93,1.93,1.78,1.89,1.93,2.05
4,P1,10/08/2025,20:30,Moreirense,Alverca,2,1,H,1,1,...,1.95,1.90,2.05,1.87,1.95,1.90,1.88,1.84,2.05,1.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,P1,27/09/2025,20:30,Estoril,Sp Lisbon,0,1,A,0,1,...,1.98,1.88,2.03,1.87,1.98,1.88,1.92,1.81,2.01,1.93
59,P1,28/09/2025,15:30,Alverca,Guimaraes,2,0,H,1,0,...,1.83,2.03,1.97,1.93,1.91,2.03,1.82,1.93,1.96,2.01
60,P1,28/09/2025,18:00,Sp Braga,Nacional,0,1,A,0,1,...,1.95,1.90,1.88,2.03,1.95,1.90,1.86,1.86,1.99,1.94
61,P1,28/09/2025,20:30,Famalicao,Rio Ave,0,0,D,0,0,...,1.83,2.03,1.87,2.05,1.85,2.03,1.81,1.91,1.93,2.04
62,P1,29/09/2025,20:00,Arouca,Porto,0,4,A,0,1,...,1.95,1.90,1.82,2.09,1.95,2.07,1.85,1.89,1.99,1.99

# 2. Read .csv from Multiple URLs with Pandas

- https://www.football-data.co.uk/mmz4281/2526/E0.csv
- https://www.football-data.co.uk/mmz4281/2526/E1.csv
- https://www.football-data.co.uk/mmz4281/2526/E2.csv

In [4]:
# link structure 
"https://www.football-data.co.uk/mmz4281/"+ "2526"+ "/"+ "E0"+ ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

## all links 
- https://www.football-data.co.uk/mmz4281/2526/E0.csv
- https://www.football-data.co.uk/mmz4281/2526/E1.csv
- https://www.football-data.co.uk/mmz4281/2526/E2.csv
- https://www.football-data.co.uk/mmz4281/2526/E3.csv
- https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [5]:
# creating the root variable (common for all link)
root = "https://www.football-data.co.uk/mmz4281/"

In [6]:
# Storing only season data
# creating a list with dynamic values (this is diff in all link)
leagues = ['E0','E1','E2','E3','EC']
frames=[] 

# looping the league and appending in frames list
for league in leagues:
    df = pd.read_csv(root +'2526'+'/'+league+'.csv')
    frames.append(df)

In [7]:
# length of the frames
len(frames)

5

In [8]:
# display 1st , 2nd and 3rd element
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,EC,27/09/2025,15:00,Sutton,Boston Utd,1,1,D,0,1,...,2.05,1.75,2.00,1.85,2.05,1.77,1.97,1.75,2.14,1.84
133,EC,27/09/2025,15:00,Truro,Morecambe,5,0,H,1,0,...,1.90,1.90,1.91,1.94,1.90,1.90,1.86,1.83,2.02,1.92
134,EC,27/09/2025,15:00,Wealdstone,Eastleigh,0,0,D,0,0,...,1.98,1.83,1.95,1.90,1.98,1.83,1.93,1.78,2.07,1.90
135,EC,27/09/2025,15:00,Yeovil,Altrincham,1,0,H,1,0,...,1.78,2.03,2.06,1.81,1.80,2.03,1.74,1.97,1.79,2.25
136,EC,27/09/2025,17:30,Forest Green,York,1,1,D,1,1,...,2.00,1.80,2.00,1.86,2.00,1.80,1.96,1.74,2.09,1.90

# Multiple Season Data

In [9]:
for season in range(20,26):
    print(str(season)+str(season+1))

2021
2122
2223
2324
2425
2526

In [10]:
# Multiple seasons
leagues = ['E0','E1','E2']
frames=[] 

for league in leagues:
    for season in range(20,26):
        df = pd.read_csv(root +str(season)+str(season+1)+'/'+league+'.csv')
        df.insert(1,'Season', season)
        frames.append(df)

In [11]:
len(frames)

18

In [12]:
frames[17]

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,25,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,25,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,25,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04
3,E2,25,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,...,1.73,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22
4,E2,25,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,...,2.00,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,E2,25,27/09/2025,15:00,Mansfield,Rotherham,2,1,H,0,...,1.95,1.90,1.88,2.02,2.00,1.90,1.94,1.79,2.04,1.94
111,E2,25,27/09/2025,15:00,Northampton,Bolton,2,0,H,0,...,1.88,1.98,1.88,2.02,1.88,1.98,1.80,1.94,1.95,2.03
112,E2,25,27/09/2025,15:00,Peterboro,Lincoln,0,3,A,0,...,2.03,1.83,2.22,1.71,2.10,1.83,2.03,1.74,2.13,1.85
113,E2,25,27/09/2025,15:00,Stockport,Reading,1,1,D,1,...,2.05,1.80,2.08,1.83,2.05,1.83,1.96,1.78,2.13,1.85
114,E2,25,27/09/2025,15:00,Wigan,Cardiff,0,2,A,0,...,1.93,1.93,1.94,1.94,1.93,1.93,1.88,1.85,2.02,1.96

In [13]:
# creating a dictionary 
dict_cont={
    'Spanish la ': 'SP1', 'Spanish SD' : 'SP2',
    'German' : 'D1', 'English prem':'E0', 'English league':'E2', 
    'English':'E3'
}

In [14]:
for league in dict_cont:
    print(dict_cont[league])

SP1
SP2
D1
E0
E2
E3

In [15]:
# storing specfic key of data 
# leagues = ['E0','E1','E2']
total_dict={}

for league in dict_cont:
    frames=[] 
    for season in range(20,26):
        df = pd.read_csv(root +str(season)+str(season+1)+'/'+ dict_cont[league] +'.csv')
        df.insert(1,'Season', season)
        frames.append(df)
    df_concat = pd.concat(frames)
    total_dict[league] = df_concat

In [16]:
total_dict

{'Spanish la ':     Div  Season        Date   Time    HomeTeam    AwayTeam  FTHG  FTAG FTR  \
 0   SP1      20  12/09/2020  15:00       Eibar       Celta     0     0   D
 1   SP1      20  12/09/2020  17:30     Granada  Ath Bilbao     2     0   H
 2   SP1      20  12/09/2020  20:00       Cadiz     Osasuna     0     2   A
 3   SP1      20  13/09/2020  13:00      Alaves       Betis     0     1   A
 4   SP1      20  13/09/2020  15:00  Valladolid    Sociedad     1     1   D
 ..  ...     ...         ...    ...         ...         ...   ...   ...  ..
 64  SP1      25  27/09/2025  20:00  Villarreal  Ath Bilbao     1     0   H
 65  SP1      25  28/09/2025  13:00   Vallecano     Sevilla     0     1   A
 66  SP1      25  28/09/2025  15:15       Elche       Celta     2     1   H
 67  SP1      25  28/09/2025  17:30   Barcelona    Sociedad     2     1   H
 68  SP1      25  28/09/2025  20:00       Betis     Osasuna     2     0   H

     HTHG  ...  BMGMCA  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  LBCD  LBCA
 0      0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 1      0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 2      0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 3      0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 4      1  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 ..   ...  ...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 64     0  ...     4.0  2.10  3.25  3.75  2.00   3.3  3.80  2.00   3.3  3.80
 65     0  ...     4.1  2.00  3.30  4.00  2.00   3.3  3.80  2.00   3.3  3.75
 66     1  ...     2.7  2.80  3.10  2.70  2.75   3.2  2.62  2.75   3.1  2.60
 67     1  ...     7.5  1.29  5.75  9.50  1.36   5.5  7.00  1.36   5.5  7.00
 68     2  ...     4.5  1.75  3.70  4.75  1.83   3.6  4.33  1.83   3.5  4.20

 [1969 rows x 162 columns],
 'Spanish SD':     Div  Season        Date   Time      HomeTeam          AwayTeam  FTHG  \
 0   SP2      20  12/09/2020  15:00  Ponferradina         Castellon     1
 1   SP2      20  12/09/2020  17:15       Leganes        Las Palmas     1
 2   SP2      20  12/09/2020  17:15      Sp Gijon          Logrones     1
 3   SP2      20  12/09/2020  20:00       Espanol          Albacete     3
 4   SP2      20  13/09/2020  11:00        Oviedo         Cartagena     0
 ..  ...     ...         ...    ...           ...               ...   ...
 72  SP2      25  28/09/2025  15:15         Cadiz             Ceuta     0
 73  SP2      25  28/09/2025  17:30      Sp Gijon          Albacete     3
 74  SP2      25  28/09/2025  17:30    Valladolid  Cultural Leonesa     0
 75  SP2      25  28/09/2025  20:00        Huesca           Granada     0
 76  SP2      25  29/09/2025  19:30       Leganes         Castellon     0

     FTAG FTR  HTHG  ...  BMGMCA  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  \
 0      2   A     1  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 1      0   H     0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 2      0   H     0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 3      0   H     2  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 4      0   D     0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 ..   ...  ..   ...  ...     ...   ...   ...   ...   ...   ...   ...   ...
 72     0   D     0  ...    3.75  1.91  3.30  3.75  2.05  3.10   3.2  2.05
 73     4   A     3  ...    3.70  1.90  3.40  3.60  1.91  3.40   3.3  1.91
 74     1   A     0  ...    6.10  1.45  4.00  6.50  1.48  4.00   5.5  1.48
 75     1   A     0  ...    3.45  2.15  3.00  3.40  2.30  2.80   3.1  2.30
 76     1   A     0  ...    2.90  2.20  3.25  3.00  2.25  3.25   2.7  2.25

     LBCD  LBCA
 0    NaN   NaN
 1    NaN   NaN
 2    NaN   NaN
 3    NaN   NaN
 4    NaN   NaN
 ..   ...   ...
 72  3.10   3.2
 73  3.40   3.3
 74  4.00   5.5
 75  2.80   3.1
 76  3.25   2.7

 [2387 rows x 162 columns],
 'German':    Div  Season        Date   Time       HomeTeam       AwayTeam  FTHG  FTAG  \
 0   D1      20  18/09/2020  19:30  Bayern Munich     Schalke 04     8     0
 1   D1      20  19/09/2020  14:30  Ein Frankfurt      Bielefeld     1     1
 2   D1      20  19/09/2020  14:30        FC Koln     Hoffenheim     2     3
 3   D1      20  19/09/2020  14:30      Stuttgart       Freiburg     2     3
 4   D1      20  19/09/2020  14:30   Union Berlin       Augsburg     1     3
 ..  ..     ...         ...    ...            ...            ...   ...   ...
 40  D1      25  27/09/2025  14:30      Wolfsburg     RB Leipzig     0     1
 41  D1      25  27/09/2025  17:30     M'gladbach  Ein Frankfurt     4     6
 42  D1      25  28/09/2025  14:30       Freiburg     Hoffenheim     1     1
 43  D1      25  28/09/2025  16:30        FC Koln      Stuttgart     1     2
 44  D1      25  28/09/2025  18:30   Union Berlin        Hamburg     0     0

    FTR  HTHG  ...  BMGMCA  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  LBCD  \
 0    H   3.0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 1    D   0.0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 2    A   1.0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 3    A   0.0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 4    A   0.0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 ..  ..   ...  ...     ...   ...   ...   ...   ...   ...   ...   ...   ...
 40   A   0.0  ...    2.50  2.55  3.80  2.45  2.60   3.6  2.50  2.60  3.60
 41   A   0.0  ...    2.30  2.80  3.75  2.25  2.87   3.7  2.25  2.87  3.70
 42   D   1.0  ...    3.00  2.25  3.40  3.10  2.30   3.3  3.10  2.30  3.25
 43   A   1.0  ...    2.60  2.60  3.60  2.50  2.50   3.7  2.60  2.50  3.60
 44   D   0.0  ...    3.65  1.95  3.60  3.60  2.00   3.5  3.70  1.95  3.50

     LBCA
 0    NaN
 1    NaN
 2    NaN
 3    NaN
 4    NaN
 ..   ...
 40  2.50
 41  2.25
 42  3.10
 43  2.50
 44  3.60

 [1575 rows x 162 columns],
 'English prem':    Div  Season        Date   Time        HomeTeam     AwayTeam  FTHG  FTAG  \
 0   E0      20  12/09/2020  12:30          Fulham      Arsenal     0     3
 1   E0      20  12/09/2020  15:00  Crystal Palace  Southampton     1     0
 2   E0      20  12/09/2020  17:30       Liverpool        Leeds     4     3
 3   E0      20  12/09/2020  20:00        West Ham    Newcastle     0     2
 4   E0      20  13/09/2020  14:00       West Brom    Leicester     0     3
 ..  ..     ...         ...    ...             ...          ...   ...   ...
 55  E0      25  27/09/2025  17:30   Nott'm Forest   Sunderland     0     1
 56  E0      25  27/09/2025  20:00       Tottenham       Wolves     1     1
 57  E0      25  28/09/2025  14:00     Aston Villa       Fulham     3     1
 58  E0      25  28/09/2025  16:30       Newcastle      Arsenal     1     2
 59  E0      25  29/09/2025  20:00         Everton     West Ham     1     1

    FTR  HTHG  ...  BMGMCA  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  LBCD  \
 0    A     0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 1    H     1  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 2    H     3  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 3    A     0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 4    A     0  ...     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 ..  ..   ...  ...     ...   ...   ...   ...   ...   ...   ...   ...   ...
 55   A     0  ...    4.75  1.73  3.75  4.80  1.75   3.6   4.6  1.75   3.6
 56   D     0  ...    6.10  1.53  4.20  6.00  1.53   4.2   6.0  1.53   4.2
 57   H     1  ...    3.25  2.25  3.20  3.40  2.25   3.2   3.4  2.20   3.2
 58   A     1  ...    2.28  3.40  3.30  2.20  3.40   3.2   2.2  3.30   3.2
 59   D     1  ...    5.40  1.65  3.90  5.25  1.67   3.8   5.0  1.67   3.8

     LBCA
 0    NaN
 1    NaN
 2    NaN
 3    NaN
 4    NaN
 ..   ...
 55   4.6
 56   6.0
 57   3.3
 58   2.2
 59   5.0

 [1960 rows x 163 columns],
 'English league':     Div  Season        Date   Time        HomeTeam            AwayTeam  FTHG  \
 0    E2      20  12/09/2020  15:00      Accrington           Peterboro     2
 1    E2      20  12/09/2020  15:00           Crewe            Charlton     0
 2    E2      20  12/09/2020  15:00       Doncaster  Milton Keynes Dons     1
 3    E2      20  12/09/2020  15:00  Fleetwood Town              Burton     2
 4    E2      20  12/09/2020  15:00      Gillingham                Hull     0
 ..   ..     ...         ...    ...             ...                 ...   ...
 110  E2      25  27/09/2025  15:00       Mansfield           Rotherham     2
 111  E2      25  27/09/2025  15:00     Northampton              Bolton     2
 112  E2      25  27/09/2025  15:00       Peterboro             Lincoln     0
 113  E2      25  27/09/2025  15:00       Stockport             Reading     1
 114  E2      25  27/09/2025  15:00           Wigan             Cardiff     0

      FTAG FTR  HTHG  ...  BMGMCA  BVCH BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  \
 0       0   H     1  ...     NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
 1       2   A     0  ...     NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
 2       1   D     0  ...     NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
 3       1   H     1  ...     NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
 4       2   A     0  ...     NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
 ..    ...  ..   ...  ...     ...   ...  ...   ...   ...   ...   ...   ...
 110     1   H     0  ...    3.60  1.95  3.5  3.75  2.05   3.5  3.60  2.00
 111     0   H     0  ...    1.76  4.80  3.6  1.73  4.50   3.6  1.80  4.50
 112     3   A     0  ...    2.38  2.88  3.3  2.40  2.90   3.3  2.40  2.90
 113     1   D     1  ...    4.80  1.57  4.0  5.50  1.61   4.2  5.00  1.61
 114     2   A     0  ...    2.55  2.63  3.3  2.63  2.62   3.4  2.62  2.62

      LBCD  LBCA
 0     NaN   NaN
 1     NaN   NaN
 2     NaN   NaN
 3     NaN   NaN
 4     NaN   NaN
 ..    ...   ...
 110   3.5  3.60
 111   3.6  1.75
 112   3.3  2.37
 113   4.0  5.00
 114   3.3  2.60

 [2875 rows x 163 columns],
 'English':     Div  Season        Date   Time    HomeTeam            AwayTeam  FTHG  \
 0    E3      20  12/09/2020  15:00      Barrow           Stevenage     1
 1    E3      20  12/09/2020  15:00      Bolton        Forest Green     0
 2    E3      20  12/09/2020  15:00    Bradford          Colchester     0
 3    E3      20  12/09/2020  15:00   Cambridge            Carlisle     3
 4    E3      20  12/09/2020  15:00  Cheltenham           Morecambe     1
 ..   ..     ...         ...    ...         ...                 ...   ...
 114  E3      25  27/09/2025  15:00  Gillingham           Harrogate     0
 115  E3      25  27/09/2025  15:00     Grimsby          Cheltenham     7
 116  E3      25  27/09/2025  15:00  Shrewsbury  Milton Keynes Dons     1
 117  E3      25  27/09/2025  15:00     Swindon             Bromley     2
 118  E3      25  27/09/2025  15:00    Tranmere           Cambridge     0

      FTAG FTR  HTHG  ...  BVCH  BVCD  BVCA  CLCH  CLCD  CLCA  LBCH  LBCD  \
 0       1   D     1  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 1       1   A     0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 2       0   D     0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 3       0   H     2  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 4       2   A     1  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
 ..    ...  ..   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...
 114     1   A     0  ...  1.67  3.60  5.25  1.73   3.7  5.00  1.73  3.60
 115     1   H     2  ...  1.45  4.33  6.50  1.50   4.4  6.00  1.50  4.33
 116     2   A     0  ...  3.00  3.30  2.30  2.90   3.4  2.37  2.90  3.30
 117     0   H     2  ...  2.10  3.60  3.20  2.10   3.7  3.25  2.05  3.70
 118     0   D     0  ...  3.13  3.13  2.38  3.00   3.2  2.40  3.00  3.20

      LBCA  Unnamed: 132
 0     NaN           NaN
 1     NaN           NaN
 2     NaN           NaN
 3     NaN           NaN
 4     NaN           NaN
 ..    ...           ...
 114  4.80           NaN
 115  6.00           NaN
 116  2.37           NaN
 117  3.25           NaN
 118  2.37           NaN

 [2879 rows x 164 columns]}

In [18]:
total_dict['Spanish SD']

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP2,20,12/09/2020,15:00,Ponferradina,Castellon,1,2,A,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP2,20,12/09/2020,17:15,Leganes,Las Palmas,1,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP2,20,12/09/2020,17:15,Sp Gijon,Logrones,1,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP2,20,12/09/2020,20:00,Espanol,Albacete,3,0,H,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP2,20,13/09/2020,11:00,Oviedo,Cartagena,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,SP2,25,28/09/2025,15:15,Cadiz,Ceuta,0,0,D,0,...,3.75,1.91,3.30,3.75,2.05,3.10,3.2,2.05,3.10,3.2
73,SP2,25,28/09/2025,17:30,Sp Gijon,Albacete,3,4,A,3,...,3.70,1.90,3.40,3.60,1.91,3.40,3.3,1.91,3.40,3.3
74,SP2,25,28/09/2025,17:30,Valladolid,Cultural Leonesa,0,1,A,0,...,6.10,1.45,4.00,6.50,1.48,4.00,5.5,1.48,4.00,5.5
75,SP2,25,28/09/2025,20:00,Huesca,Granada,0,1,A,0,...,3.45,2.15,3.00,3.40,2.30,2.80,3.1,2.30,2.80,3.1
76,SP2,25,29/09/2025,19:30,Leganes,Castellon,0,1,A,0,...,2.90,2.20,3.25,3.00,2.25,3.25,2.7,2.25,3.25,2.7