In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('population_total.csv')

In [4]:
df

            country    year    population
0             China  2020.0  1.439324e+09
1             China  2019.0  1.433784e+09
2             China  2018.0  1.427648e+09
3             China  2017.0  1.421022e+09
4             China  2016.0  1.414049e+09
...             ...     ...           ...
4180  United States  1965.0  1.997337e+08
4181  United States  1960.0  1.867206e+08
4182  United States  1955.0  1.716853e+08
4183          India  1960.0  4.505477e+08
4184          India  1955.0  4.098806e+08

[4185 rows x 3 columns]

# Making a Pivot Table

.pivot(): Returns reshaped DataFrame organized by given index / column values ("pivot without aggregation")

In [7]:
df.dropna(inplace=True)

In [15]:
df['country'].unique().tolist()

['China',
 'France',
 'Myanmar',
 'South Africa',
 'Tanzania',
 'Italy',
 'South Korea',
 'Kenya',
 'United Kingdom',
 'Egypt',
 'Germany',
 'Vietnam',
 'DR Congo',
 'Thailand',
 'Holy See',
 'Iran',
 'Turkey',
 'Tokelau',
 'Niue',
 'Saint Pierre & Miquelon',
 'Saint Helena',
 'Montserrat',
 'Falkland Islands',
 'Wallis & Futuna',
 'Saint Barthelemy',
 'Nauru',
 'Cook Islands',
 'Tuvalu',
 'Anguilla',
 'Caribbean Netherlands',
 'British Virgin Islands',
 'Gibraltar',
 'San Marino',
 'Palau',
 'Liechtenstein',
 'Saint Martin',
 'Turks and Caicos',
 'Monaco',
 'Sint Maarten',
 'Faeroe Islands',
 'Saint Kitts & Nevis',
 'American Samoa',
 'Greenland',
 'Northern Mariana Islands',
 'Marshall Islands',
 'Bermuda',
 'Cayman Islands',
 'Dominica',
 'Andorra',
 'Isle of Man',
 'Antigua and Barbuda',
 'Seychelles',
 'U.S. Virgin Islands',
 'Tonga',
 'St. Vincent & Grenadines',
 'Grenada',
 'Kiribati',
 'Curaçao',
 'Aruba',
 'Guam',
 'Channel Islands',
 'Saint Lucia',
 'Samoa',
 'Sao Tome & Principe',
 'Mayotte',
 'French Polynesia',
 'Barbados',
 'Vanuatu',
 'New Caledonia',
 'Iceland',
 'Martinique',
 'Bahamas',
 'French Guiana',
 'Belize',
 'Brunei ',
 'Malta',
 'Guadeloupe',
 'Maldives',
 'Cabo Verde',
 'Suriname',
 'Western Sahara',
 'Luxembourg',
 'Montenegro',
 'Macao',
 'Bhutan',
 'Comoros',
 'Réunion',
 'Solomon Islands',
 'Guyana',
 'Fiji',
 'Djibouti',
 'Eswatini',
 'Cyprus',
 'Mauritius',
 'Timor-Leste',
 'Estonia',
 'Trinidad and Tobago',
 'Equatorial Guinea',
 'Bahrain',
 'Latvia',
 'Guinea-Bissau',
 'Slovenia',
 'North Macedonia',
 'Gabon',
 'Botswana',
 'Gambia',
 'Namibia',
 'Lesotho',
 'Lithuania',
 'Puerto Rico',
 'Albania',
 'Qatar',
 'Jamaica',
 'Armenia',
 'Mongolia',
 'Bosnia and Herzegovina',
 'Uruguay',
 'Eritrea',
 'Georgia',
 'Moldova',
 'Croatia',
 'Kuwait',
 'Panama',
 'Mauritania',
 'New Zealand',
 'Central African Republic',
 'Ireland',
 'Liberia',
 'Costa Rica',
 'State of Palestine',
 'Oman',
 'Norway',
 'Slovakia',
 'Congo',
 'Finland',
 'Denmark',
 'Singapore',
 'Turkmenistan',
 'El Salvador',
 'Kyrgyzstan',
 'Nicaragua',
 'Lebanon',
 'Libya',
 'Bulgaria',
 'Paraguay',
 'Laos',
 'Hong Kong',
 'Sierra Leone',
 'Togo',
 'Switzerland',
 'Israel',
 'Serbia',
 'Papua New Guinea',
 'Austria',
 'Belarus',
 'Tajikistan',
 'Hungary',
 'United Arab Emirates',
 'Honduras',
 'Sweden',
 'Azerbaijan',
 'Portugal',
 'Jordan',
 'Greece',
 'Czech Republic (Czechia)',
 'Dominican Republic',
 'South Sudan',
 'Cuba',
 'Haiti',
 'Belgium',
 'Bolivia',
 'Tunisia',
 'Burundi',
 'Benin',
 'Rwanda',
 'Guinea',
 'Zimbabwe',
 'Somalia',
 'Chad',
 'Cambodia',
 'Senegal',
 'Netherlands',
 'Syria',
 'Ecuador',
 'Guatemala',
 'Zambia',
 'Kazakhstan',
 'Chile',
 'Malawi',
 'Romania',
 'Mali',
 'Burkina Faso',
 'Sri Lanka',
 'Taiwan',
 'Niger',
 'Australia',
 'North Korea',
 "Côte d'Ivoire",
 'Cameroon',
 'Madagascar',
 'Venezuela',
 'Nepal',
 'Yemen',
 'Ghana',
 'Mozambique',
 'Malaysia',
 'Angola',
 'Peru',
 'Uzbekistan',
 'Saudi Arabia',
 'Morocco',
 'Canada',
 'Poland',
 'Afghanistan',
 'Iraq',
 'Ukraine',
 'Sudan',
 'Algeria',
 'Argentina',
 'Uganda',
 'Spain',
 'Colombia',
 'Philippines',
 'Ethiopia',
 'Japan',
 'Mexico',
 'Russia',
 'Bangladesh',
 'Nigeria',
 'Brazil',
 'Pakistan',
 'Indonesia',
 'United States',
 'India']

In [16]:
df_pivot = df.pivot(index='year', columns='country', values='population')

In [20]:
df_pivot = df_pivot[['India', 'United States', 'China', 'Indonesia', 'Brazil']]

In [23]:
df_pivot.round(2)

country         India  United States         China    Indonesia       Brazil
year
1955.0   4.098806e+08    171685336.0  6.122416e+08   77273425.0   62533919.0
1960.0   4.505477e+08    186720571.0  6.604081e+08   87751068.0   72179226.0
1965.0   4.991233e+08    199733676.0  7.242190e+08  100267062.0   83373530.0
1970.0   5.551898e+08    209513341.0  8.276014e+08  114793178.0   95113265.0
1975.0   6.231029e+08    219081251.0  9.262409e+08  130680727.0  107216205.0
1980.0   6.989528e+08    229476354.0  1.000089e+09  147447836.0  120694009.0
1985.0   7.843600e+08    240499825.0  1.075589e+09  164982451.0  135274080.0
1990.0   8.732778e+08    252120309.0  1.176884e+09  181413402.0  149003223.0
1995.0   9.639226e+08    265163745.0  1.240921e+09  196934260.0  162019896.0
2000.0   1.056576e+09    281710909.0  1.290551e+09  211513823.0  174790340.0
2005.0   1.147610e+09    294993511.0  1.330776e+09  226289470.0  186127103.0
2010.0   1.234281e+09    309011475.0  1.368811e+09  241834215.0  195713635.0
2015.0   1.310152e+09    320878310.0  1.406848e+09  258383256.0  204471769.0
2016.0   1.324517e+09    323015995.0  1.414049e+09  261556381.0  206163053.0
2017.0   1.338677e+09    325084756.0  1.421022e+09  264650963.0  207833823.0
2018.0   1.352642e+09    327096265.0  1.427648e+09  267670543.0  209469323.0
2019.0   1.366418e+09    329064917.0  1.433784e+09  270625568.0  211049527.0
2020.0   1.380004e+09    331002651.0  1.439324e+09  273523615.0  212559417.0