In [15]:
import pandas as pd
df = pd.read_csv('organizations.csv')
df.head()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991

1. Math operation

1.1 Operation in column

In [16]:
# Select a column and calculate total sum
df['Number of employees'].sum()

np.int64(4964996)

In [20]:
# count, mean, std, max, min
df['Number of employees'].count()
df['Number of employees'].mean()
df['Number of employees'].std()
df['Number of employees'].max()
df['Number of employees'].min()

np.int64(1)

In [21]:
# easiest calculation with describe() 
df.describe()

             Index      Founded  Number of employees
count  1000.000000  1000.000000          1000.000000
mean    500.500000  1995.852000          4964.996000
std     288.819436    15.096026          2812.789035
min       1.000000  1970.000000             1.000000
25%     250.750000  1983.000000          2612.000000
50%     500.500000  1996.000000          4941.000000
75%     750.250000  2009.000000          7348.250000
max    1000.000000  2022.000000          9952.000000

1.2 operation in rows

In [24]:
# adding the rows (adding the rows of 3 columns)
df['Index']+ df['Founded']+df['Number of employees']

0       8833
1       9966
2       7113
3      11088
4       9006
       ...
995     9541
996    12735
997     8334
998     6837
999     7486
Length: 1000, dtype: int64

In [25]:
# calculating the mean for above and assigning it to a variable
average = (df['Index']+ df['Founded']+df['Number of employees'])/3

In [27]:
# creating a new column 
df['Average']= average 
round(df,2) # or df.round(2)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees,Average
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852,2944.33
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994,3322.00
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105,2371.00
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069,3696.00
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991,3002.00
...,...,...,...,...,...,...,...,...,...,...
995,996,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547,3180.33
996,997,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723,4245.00
997,998,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355,2778.00
998,999,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825,2279.00
999,1000,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467,2495.33